name: Floating Tags
# This workflow manages floating tags for this project. When digests
# change in ./containertags/* files, the associated tag is synced
# in the container registry.
on:
  push: # Includes when PRs get merged to the branches.
    branches:
      - "ghactions"
jobs:
  move-tag-ghactions:
    name: "Update Tag: ghactions"
    uses: ./.github/workflows/manage-floating-tag.yaml
    with:
      tag: ghactions
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  

  move-tag-dev:
    name: "Update Tag: dev"
    uses: ./.github/workflows/manage-floating-tag.yaml
    with:
      tag: dev
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}

  move-tag-test:
    name: "Update Tag: test"
    uses: ./.github/workflows/manage-floating-tag.yaml
    with:
      tag: test
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}